### ISSUE TITLE
Document Control Reports

### ISSUE THREAD

**Issue by delcabo** [caom92/FoodSafetyManual#346]
Hola buen dia Equipo

Saben revisando como Director la opcion de reportes, en el caso de document control para LAW
salen de BCN

![image](https://user-images.githubusercontent.com/28766240/29936799-585c55dc-8e38-11e7-99ae-3b8d469a6d06.png)

**Comment by caom92** [comment]
Intenté replicar el problema pero no pude; inicié sesión con su cuenta, cambié de zona a LAW, luego fui a la pantalla de reportes de Doc Control, ingresé las fechas y me devolvió correctamente los reportes de LAW. Luego, en esa misma pantalla cambié a BCN y volví a hacer clic en Open Report y me retornó correctamente reportes de BCN. Finalmente, me regresé a LAW y volví a hacer clic en Open Report y aún así me mostró únicamente reportes de LAW. ¿Hizo alguna otra cosa que yo hubiera omitido al intentar replicar el problema?

**Comment by caom92** [comment]
Ya lo pude reproducir, comenzaremos a trabajar en arreglarlo

**Comment by caom92** [comment]
Para reproducir el bug simplemente es necesario cambiar de zona inmediatamente después de entrar a la página de bitácoras; el cambio de zona no se realizará

**Comment by caom92** [comment]
Arreglado en cliente 2
