### ISSUE TITLE
Tiempo Activo en capturas!!!

### ISSUE THREAD

**Issue by delcabo** [caom92/FoodSafetyManual#390]
Es posible que el sistema tenga un AUTOREFRESH o Reconect sin perder datos!!!  cuando se tuvo un tiempo de inactividad! (claro sin cerrar session)

:)

**Comment by caom92** [comment]
El sistema actualmente **no** está programado para expirar la sesión del usuario por inactividad, es probable que lo está experimentando sea el síntoma de un problema diferente, pero hasta no realizar las pruebas necesarias no podremos diagnosticar cuál es el problema exactamente. 

La única ocasión donde el usuario perderá su sesión es en los siguientes casos: 
- Cuando el usuario explícitamente cierra sesión en el menú lateral de navegación
- Cuando el usuario cierra el navegador o apaga la computadora
- Cuando el usuario abre una sesión nueva en *otra pestaña*; en este caso, la sesión vieja se cierra y sólamente se preserva la sesión nueva

Mientras el usuario no haga ninguna de estas cosas, su sesión **debe** permanecer **abierta**, sin importar cuánto tiempo de inactividad pase.
