### ISSUE TITLE
Aging Product  (Se empalma fecha) y se User not logged in

### ISSUE THREAD

**Issue by delcabo** [caom92/FoodSafetyManual#393]
revision con el usuario, no se salio en ningun momento de la session, lo que si estoy seguro es que es muy lento para la captura!...

![image](https://user-images.githubusercontent.com/28766240/31400042-1835413c-ada3-11e7-80a0-c9f015b4fd8d.png)

**Comment by caom92** [comment]
Corregido en el cliente 2
