### ISSUE TITLE
Poner la hora en color negro bold

### ISSUE THREAD

**Issue by delcabo** [caom92/FoodSafetyManual#396]
en las bitacoras de:
Basculas
Tijeras
Termometros
Vidrios y plasticos
ATP
y 
Organic Program Verification & SRRC

![image](https://user-images.githubusercontent.com/28766240/32118072-4e53db56-bb05-11e7-9a0d-d3a48318d510.png)

**Comment by VMiracle** [comment]
Terminado y en el servidor.

[Tiempo total de desarrollo: 30 minutos]
