### ISSUE TITLE
ajuste en PDF  Cold Room Temperature Control

### ISSUE THREAD

**Issue by delcabo** [caom92/FoodSafetyManual#400]
se puede ajustar:
Hora al centro
Item # mas largo
reducir deficiencias y Acciones Correctivas... 

![image](https://user-images.githubusercontent.com/28766240/32456083-2cc5d6d4-c2d9-11e7-8105-5afed80fa703.png)

**Comment by VMiracle** [comment]
Buen día, Julio.

En cuanto a lo de la hora alineada verticalmente al centro; es una característica que no se puede implementar. 

Con respecto al tamaño de las columnas, quisiera saber qué tan más ancha quiere que sea la del # de item.

**Comment by delcabo** [comment]
Hola

Enterado con la fecha
lo unico que seria agrandar seria la columna de "#" y reducir Deficiencias y acciones un poco mas!

saludos
