### ISSUE TITLE
Ajuste PDF: Daily Thermometer Calibration Verification Check

### ISSUE THREAD

**Issue by delcabo** [caom92/FoodSafetyManual#401]
se puede ajustar

Hora: al centro de la columna"
encabezado en Espanol "Prueba del Metodo de punto de Hielo"  a "Metodo de Prueba con Hielo (°F)"
el de Ingles esta bien  solo ponerles despues de "test" = "test (°F)"

![image](https://user-images.githubusercontent.com/28766240/32456321-0c051d96-c2da-11e7-94d3-a65a15ec7da3.png)

**Comment by delcabo** [comment]
TARDES....

El sistema pone en Calibracion todo el tiempo SI, aun cuando capturamos un NO... :(
![image](https://user-images.githubusercontent.com/28766240/32465090-253de8de-c2f7-11e7-9f2c-ad0d885fbd4e.png)

**Comment by VMiracle** [comment]
Con respecto a centrar la hora, es una característica que no se puede implementar en el PDF.

El cambio de texto fue realizado (si no es visible de inmediato, es posible que tenga que limpiar el caché)

El error con la calibración ya fue corregido; se trataba de un error en el despliegue, así que los datos marcados como si/no de fechas anteriores se mostraran correctamente a partir de ahora

[Tiempo total de desarrollo: 40 minutos]
